### ISSUE TITLE
Remove Newtonsoft.Json 9.0.0.0 signed assembly dependency

### ISSUE THREAD

**Issue by i2van** [serilog/serilog-formatting-compact-reader#22]
Current package 1.0.3 requires only Newtonsoft.Json 9.0.0.0 signed assembly; otherwise binding redirect should be made, which sometimes is undesirable.

**Comment by nblumhardt** [comment]
Thanks for the note, @i2van. At the moment the implementation of this package makes this infeasible (it's highly-dependent on Newtonsoft.Json). I don't think this is a change we'll be able to make in the near future, but good to have the feedback, thanks!

**Comment by LiorBanai** [comment]
Can the Newtonsoft.Json version be updated with the latest version?

**Comment by nblumhardt** [comment]
Hi Lior, thanks for the note.

I think, currently, we'd introduce more breakage by moving the package dependency forwards, than by leaving things as-is and using a binding redirect. Is the dependency version causing issues in your app that aren't resolved by binding redirects (which the recent CSPROJ versions should add automatically)?

I am wondering whether, if we're going to make breaking changes to this package, we might not be better off building v2 on _System.Text.Json_ ...?

Cheers,
Nick

**Comment by LiorBanai** [comment]
Yeah, if by bumping up the version there are going to be breaking changes I agree that in this case it is even better to go  directly to System.Text.Json (which has different defaults than Newtonsoft.)..

**Comment by Numpsy** [comment]
Is the original issue here fixed now? (v3 seems to depend on Newtonsoft 13.0.3)

**Comment by nblumhardt** [comment]
Closing this one as stale; thanks :+1:
