### ISSUE TITLE
Analogy Log Viewer Parser

### ISSUE THREAD

**Issue by LiorBanai** [serilog/serilog-formatting-compact-reader#23]
Hi,
I have added a parser for this formatting base on your work:
https://github.com/Analogy-LogViewer/Analogy.LogViewer.Serilog

just wanted to update in case people are still using this format since the repository seems not to be updated for some time :)

the parsing of the example:
![CompactFormat](https://user-images.githubusercontent.com/36262995/76024987-b5210680-5f34-11ea-8a83-4b893dcd3d92.jpg)

**Comment by nblumhardt** [comment]
Thanks!
