### ISSUE TITLE
locked files?

### ISSUE THREAD

**Issue by vip32** [serilog/serilog-formatting-compact-reader#4]
can it read from locked files? as this could be the case if the file is also being written to (as we see with the rollingfile sink for example).

**Comment by nblumhardt** [comment]
Hi Vincent,

Yes, the reader only requires a `TextReader` so this can be opened over a file with `FileAccess.Read`:

```csharp
using (var reader = new StreamReader(File.Open("file.log", FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
{
}
```

HTH!
Nick

**Comment by vip32** [comment]
ah, yes. that is how it is supped to work :)
thx for the info

**Comment by nblumhardt** [comment]
Great, thanks for the follow-up 👍
