### ISSUE TITLE
JavaScript version of this library

### ISSUE THREAD

**Issue by lonix1** [serilog/serilog-formatting-compact-reader#46]
I'm trying to build a very simple UI for showing our logs inline in our Razor Pages app. I'm aware of the [serilog-ui](https://github.com/serilog-contrib/serilog-ui) project but it's not a good fit for us (too complicated).

This library allows us to render events on the server. But since structured log events are already stored as JSON in our database, it makes sense to simply send them as is, and thus offload the rendering burden to the browser.

Does anyone know of a js port of this library? There are so many serilog-related libraries and contrib repos and so on, so I'd like to know whether something like that exists before writing one from scratch.

*(I'm posting here as there's no "Discussions" tab for this repo... Sorry! Please close once you've seen it.)*

**Comment by nblumhardt** [comment]
Howdy! In case it helps - the most "bespoke" part of the task is probably message template parsing and rendering. These JavaScript/TypeScript projects include some message template support you might check out:

 * https://github.com/structured-log/structured-log
 * https://github.com/davisb10/serilogger

HTH

**Comment by lonix1** [comment]
Thanks that looks very useful! :smile:

**Comment by lonix1** [comment]
Posting this in case it help anyone else, or someone finds a better way.

I looked at the source for https://github.com/serilog/serilog-formatting-compact-reader in the hopes of porting to javascript, but ultimately https://github.com/davisb10/serilogger does most of the work already.

One can extract the [messageTemplate](https://github.com/davisb10/serilogger/blob/ea17183f55fe0c4cf6bbabcfde98e20833b583e6/src/messageTemplate.ts) class from that project:
```js
class MessageTemplate {

  tokenizer = /{@?\w+}/g;

  constructor(messageTemplate) {
    if (messageTemplate === null || !messageTemplate.length) throw new Error('Argument "messageTemplate" is required.');
    this.raw    = messageTemplate;
    this.tokens = this.tokenize(messageTemplate);
  }

  render(properties) {
    if (!this.tokens.length) {
      return this.raw;
    }
    properties = properties || {};
    const result = [];
    for (let i = 0; i < this.tokens.length; ++i) {
      const token = this.tokens[i];
      if (typeof token.name === 'string') {
        if (properties.hasOwnProperty(token.name)) {
          result.push(this.toText(properties[token.name]));
        }
        else {
          result.push(token.raw);
        }
      }
      else {
        result.push(token.text);
      }
    }
    return result.join('');
  }

  tokenize(template) {
    const tokens = [];
    let result;
    let textStart = 0;
    while ((result = this.tokenizer.exec(template)) !== null) {
      if (result.index !== textStart) {
        tokens.push({ text: template.slice(textStart, result.index) });
      }
      let destructure = false;
      let token = result[0].slice(1, -1);
      if (token.indexOf('@') === 0) {
        token = token.slice(1);
        destructure = true;
      }
      tokens.push({
        name: token,
        destructure,
        raw: result[0]
      });
      textStart = this.tokenizer.lastIndex;
    }
    if (textStart >= 0 && textStart < template.length) {
      tokens.push({ text: template.slice(textStart) });
    }
    return tokens;
  }

  toText(property) {
    if (typeof property === 'undefined')            return 'undefined';
    if (property === null)                          return 'null';
    if (typeof property === 'string')               return property;
    if (typeof property === 'number')               return property.toString();
    if (typeof property === 'boolean')              return property.toString();
    if (typeof property.toISOString === 'function') return property.toISOString();
    if (typeof property === 'object')               return JSON.stringify(property);
    return property.toString();
  }

}
```

And to use it:
```js
let messageTemplate = new MessageTemplate('Hello {What}');
let properties = { "What": "World!" };
let message = messageTemplate.render(properties);
console.log(message);            // Hello World!
```

It's not perfect though as it doesn't support [renderings](https://github.com/davisb10/serilogger/issues/39).
