### ISSUE TITLE
Minimize dependencies

### ISSUE THREAD

**Issue by srogovtsev** [serilog/serilog-formatting-compact-reader#7]
For some reason `Serilog.Formatting.Compact.Reader` NuGet package adds another ~50 packages to my project, although I suppose it really need only a bunch of those. May be a dependency on `NETStandard.Library` is to blame?

**Comment by nblumhardt** [comment]
Yes, I think we can eliminate this one. I'll have a look into it. Thanks!

**Comment by nblumhardt** [comment]
1.0.0-dev-00010 should now fix this. If the build works for you - I think we could almost call this one a "1.0". ( #9 )

**Comment by srogovtsev** [comment]
Seems like the build works fine for me (and I now have much smaller dependency list!)

**Comment by nblumhardt** [comment]
Thanks :+1:
